# Generated by Django 5.0 on 2024-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usermember',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usermember',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usermember',
            name='userpassword',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
