# Generated by Django 5.0 on 2024-01-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_usermember_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermember',
            old_name='c',
            new_name='c1',
        ),
    ]
