# Generated by Django 5.0 on 2024-01-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_c_usermember_c1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermember',
            old_name='c1',
            new_name='c',
        ),
    ]
