# Generated by Django 5.0 on 2024-01-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_rename_c1_usermember_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='userpassword',
        ),
    ]
